# Generated by Django 5.1.3 on 2024-12-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_order_description_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_access_customer_page', 'Can access customer page'), ('can_access_freelancer_page', 'Can access freelancer page')]},
        ),
    ]
