# Generated by Django 5.1.3 on 2024-12-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_access_customer_page', 'Can access customer page'), ('can_access_freelancer_page', 'Can access freelancer page'), ('can_delete_customer_page', 'Can Delete customer page'), ('can_delete_freelancer_page', 'Can Delete freelancer page')]},
        ),
    ]
