# Generated by Django 5.1.3 on 2024-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, default='service_default.jpg', null=True, upload_to=''),
        ),
    ]
